dist: trusty
sudo: false

language: node_js
node_js:
  - "6"

services:
  - rabbitmq

install:
  - NODE_ENV=development npm i
  - npm install -g codecov

script:
  - npm run lint
  - npm test
  - codecov -t $CODE_COV_TOKEN
